### PR TITLE
Sync with TUD and update to feather board

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
This syncs with all the non-TUD specific changes (ie, anything that isn't 00-*) and updates the target board to the `feather-nrf52840-sense`,

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Currently I am experiencing an issue with my feather board running `02-timers`... It would appear that providing a reset (via `make reset` or pressing the reset button) while using `ZIMER_MSEC` actually freezes the program.  When plugging and unplugging the USB everything seems to function correctly.  This could be related to the cold-start/warm-start problem with saul @MichelRottleuthner experienced.  Further investigation is needed.

**Comment by mguetschow** [comment]
Just for the record, the commits are taken from https://github.com/netd-tud/WSN-exercises

**Comment by mguetschow** [comment]
> Currently I am experiencing an issue with my feather board running `02-timers`... It would appear that providing a reset (via `make reset` or pressing the reset button) while using `ZIMER_MSEC` actually freezes the program. When plugging and unplugging the USB everything seems to function correctly. This could be related to the cold-start/warm-start problem with saul @MichelRottleuthner experienced. Further investigation is needed.

Can confirm this locally: "This is a timers example" is still printed but everything afterwards (blinking led, reporting timeout) doesn't happen.

**Comment by MrKevinWeiss** [comment]
Unfortunately I will be available only on Tuesday to look into it.  Can we try to offload this task to someone who is not busy? (or who is busy but also knowledgeable @MichelRottleuthner )

**Comment by MichelRottleuthner** [comment]
Hmm I tried hard but I could not reproduce the timer hang - not even a single time. I tried with up-to date docker build and also with my local arm-none-eabi-gcc 13.2.0.
As you mentioned SAUL I also tried 04-saul and there indeed one of the board gets stuck without ever printing anything. Warm/cold boot doesn't affect it there. Looking closer I guess we have an issue related to different board revisions :roll_eyes: 

Adafruit mentions [here](https://learn.adafruit.com/adafruit-feather-sense/overview):
> As of January 10, 2024 - We have replaced the [discontinued LSM6DS33](https://www.adafruit.com/product/4480) with an [LSM6DS3TR-C 6 DoF sensor](https://www.adafruit.com/product/4503).

We have a few rev. B (black PCB) and now many new rev. C (blue PCB). Unfortunately the accel/gyro sensor was swapped for a different model, which may require further extensions to the lsm6dsxx driver (similar to https://github.com/RIOT-OS/RIOT/pull/20170). Rev. C is the one that gets stuck with 04-saul.

@mguetschow which board revision do you guys have at TUD?

**Comment by mguetschow** [comment]
Thanks a lot for looking into this @MichelRottleuthner !

> @mguetschow which board revision do you guys have at TUD?

We have black PCBs and I can find a B inside a circle on the lower-left corner of the back side. I guess that means we have rev. B boards, or how else could I find it out?

**Comment by mguetschow** [comment]
> Hmm I tried hard but I could not reproduce the timer hang - not even a single time. I tried with up-to date docker build and also with my local arm-none-eabi-gcc 13.2.0.

That was a very good hint, I can confirm that it doesn't crash with `BUILD_IN_DOCKER=1`, but with my locally installed arm-none-eabi-gcc 12.2.1 (Debian user here) it does. Not sure how to go on from here then.

**Comment by mguetschow** [comment]
Interestingly enough, I also don't encounter the problem on the oldstable Raspberry Pi OS with arm-none-eabi-gcc 8.3.1.

**Comment by MichelRottleuthner** [comment]
> We have black PCBs and I can find a B inside a circle on the lower-left corner of the back side. I guess that means we have rev. B boards, or how else could I find it out?

Yes that's exactly how I checked it. The circled letter next to the D2 pin indeed gives you the revision. Perfect. so you have a large amount of rev.B and we have a large amount of rev.C :facepalm: :sweat_smile:

**Comment by mguetschow** [comment]
> This could be related to the cold-start/warm-start problem with saul @MichelRottleuthner experienced.

Could you elaborate what this was/is about? We just encountered an issue with `04-saul` not printing anything on warm-start while it works as expected on cold-start. This happens when compiled with `arm-none-eabi-gcc 12.2.1`, but not in Docker (`10.3.1`) nor on Raspberry Pi OS oldstable (`8.3.1`).

So turns out gcc in Docker is actually older than my local one, and we should probably investigate these problems further for the future.

**Comment by mguetschow** [comment]
> So turns out gcc in Docker is actually older than my local one, and we should probably investigate these problems further for the future.

Although @MichelRottleuthner's `13.2.0` worked for `02-timer` at least.

For `04-saul`, have you tried flashing the given example that only uses the temperature sensor, or the extended one with accelerometer readings added? Might or not make a difference since I'd guess all SAUL-registered sensors are automatically initialized on boot?

**Comment by MrKevinWeiss** [comment]
I also think we make need one of these interactive sync module additions since we always seem to lose the initial output due to the "high_level_stdio" with pyterm...

**Comment by MrKevinWeiss** [comment]
Working on task 08 with a current diff of:
```diff
diff --git a/08-coap-basic/client.c b/08-coap-basic/client.c
index 06902bb..a6e67ba 100644
--- a/08-coap-basic/client.c
+++ b/08-coap-basic/client.c
@@ -109,7 +109,7 @@ static size_t _send(uint8_t *buf, size_t len, char *addr_str, char *port_str)
         return 0;
     }
 
-    bytes_sent = gcoap_req_send(buf, len, &remote, _resp_handler, NULL);
+    bytes_sent = gcoap_req_send(buf, len, &remote, _resp_handler, NULL, GCOAP_SOCKET_TYPE_UNDEF);
     if (bytes_sent > 0) {
         req_count++;
     }
diff --git a/RIOT b/RIOT
index 833571f..a9b9569 160000
--- a/RIOT
+++ b/RIOT
@@ -1 +1 @@
-Subproject commit 833571f630d8770e1cb216d4f77a75500e945902
+Subproject commit a9b956932d7af293bb0530cff462e447edcf88cd
```

**Comment by MrKevinWeiss** [comment]
So just about fully tested, we need some workarounds and probably can fix the root causes later...

**Pull request merged**
