### PR TITLE
Add Rust versions of the examples

### PR DESCRIPTION
**Pull request by chrysn**
The Rust examples are kept as parallel exercises, so that it is up to the user to pick their language among those languages supported.

The examples are generally kept close to the C examples (except for example where doing #7 differently). The SAUL example has a 5th task that pulls in SAUL actuators.

There is quite some duplication in the README texts, and just enough variation that we can't symlink them. I don't have any good plan for maintaining them other than awareness (at latest in PR reviewers) that updates here might also require updates there -- then again, as there is also duplication between the examples, that awareness is probably here anyway.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Nice, give me some time to go through it!

**Review by MrKevinWeiss — COMMENTED** [review]
Stumbled a bit on rust04-saul Task 5 but I guess the idea here is to force people to actually think.  Co-pilot could figure it out so I think it is OK.

One other suggestion would be being more explicit with the types rather than making everything `let`... but that is a `__weak__` suggestion.


Long story short everything works (on master) and I would be OK merging this in as is or if you want to adapt it slightly.

**Comment by chrysn** [comment]
That (from a compiler PoV needless) type annotations are helpful is
something I've gotten from other sides as well -- so yes, will update.

What do you mean by the copy-paste info item?

**Comment by MrKevinWeiss** [comment]
No point waiting I guess :)

**Pull request merged**
